[package]
name = "data-getter"
version = "1.0.1"
authors = ["pewpew79 <grigoriev.d3@mail.ru>"]
edition = "2018"


[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
serde_yaml = "0.8.11"
serde_json = "1.0.41"
rayon = "1.2.0"
