[package]
name = "data-getter"
version = "1.0.3"
authors = ["pewpew79 <grigoriev.d3@mail.ru>"]
edition = "2018"



[dependencies]
rayon = "^1.5"
serde_yaml = "^0.8"
serde_json = "^1.0"
clap = { version = "^2.33", features = ["yaml"] }
