[build]
target = "x86_64-pc-windows-gnu"



[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = [
    "-Clto=thin",
    "-Ctarget-feature=+crt-static",
    "-Cembed-bitcode=yes"
]


[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = [
    "-Ctarget-feature=+crt-static",
    "-Cembed-bitcode=yes"
]
